apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: webapp-1-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: webapp-1
    spec:
      containers:
      - name: webapp-1
        image: amitsaha/webapp1:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /_status/healthcheck/
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 1
