apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: apigateway
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
      - name: apigateway
        image: amitsaha/apigateway
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        livenessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 30
          timeoutSeconds: 1
